name: Проверка кода

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Проверка оценки Flake8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2

    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Клонирование репозитория
      run: |
        git clone https://github.com/khatip86/project_hub.git
        cd project_hub

    - name: Запуск Flake8
      run: |
        flake8 --count --select=E9,F63,F722,F821 --show-source --statistics

    - name: Get Flake8 score
      run: |
        flake8 --count --select=E9,F63,F722,F821 --show-source --statistics | grep "total" | awk '{print $2}' > score.txt
        score=$(cat score.txt)
        echo "Flake8 score: $score"

    - name: Check score and comment
      run: |
        if [[ $score -eq 0 ]]; then
          echo "Код успешно прошел проверку!"
        else
          echo "Необходимо пересмотреть код."
          exit 1
        fi
