name: Pylint Check

on:
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pylint

      - name: Run Pylint
        run: pylint --exit-zero main.py

      - name: Check Pylint score
        run: |
          score=$(pylint --output-format=json main.py | jq .[0].global_note)
          if (( $(echo "$score > 8.5" | bc -l) )); then
            echo "Pylint score is above 8.5"
          else
            echo "Pylint score is below 8.5. Code needs further checking."
            exit 1
          fi
