name: Проверка кода

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Проверка оценки Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2
      
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Запуск Pylint
      run: |
        score=$(pylint your_code.py --score=n)
        echo "Оценка Pylint: $score"
        if (( $(echo "$score >= 8.5" | bc) )); then
          echo "Проверка прошла успешно!"
        else
          echo "Пересмотрите код..."
          exit 1
        fi
