name: Pylint Check

on:
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pylint

      #- name: Run Pylint
       # run: pylint --exit-zero main.py

      - name: Check Pylint score
        run: |
          pylint_output=$(pylint --output-format=json main.py)
          score=$(echo "$pylint_output" | jq -r .[0].global_note)
          echo "Current Pylint score is: $score"
      
          if (( $(echo "$score >= 8.5" | bc -l) )); then
            echo "Проверка прошла успешно!"
          else
            echo "Пересмотрите код..."
            exit 1
          fi
