name: Проверка кода

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Проверка оценки Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2

    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Запуск Pylint
      run: |
        set -x
        pylint_score=$(pylint src/app/main.py --score=n)
        echo "Pylint score: $pylint_score"
