name: Проверка кода

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Проверка оценки Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v2

    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Клонирование репозитория
      run: |
        git clone https://github.com/khatip86/project_hub.git
        cd project_hub

    - name: Запуск Pylint
      run: |
        find . -name "*.py" -exec pylint {} --score=n \;

    - name: Get Pylint score
      run: |
        score=$(find . -name "*.py" -exec pylint {} --score=n \; | cut -d" " -f2 | sort -nr | head -1)
        echo "Pylint score: $score"

    - name: Запуск Pylint
      run: |
        if (( $(echo "$score >= 8.5" | bc -l) )); then
          echo "Код успешно прошел проверку!"
        else
          echo "Необходимо пересмотреть код."
          exit 1
        fi

